name: CI

on:
   push:
      branches: [main]

jobs:
   build:
      runs-on: ubuntu-latest

      steps:
         - uses: actions/checkout@v3

         - name: Setup Node.js
           uses: actions/setup-node@v3
           with:
              node-version: "20.x"
              cache: "yarn"

         - name: Install System Dependencies
           run: |
              sudo apt-get update
              sudo apt-get install -y libvips-dev

         - name: Clean and Install Dependencies
           run: |
              rm -rf node_modules .cache .tmp
              yarn

         - name: Run Build
           run: yarn build

         - name: Run Tests
           run: yarn test:unit --coverage

         - name: Copy to Digital Ocean
           uses: appleboy/scp-action@v1
           with:
              host: ${{ secrets.HOST }}
              username: ${{ secrets.USERNAME }}
              port: 22
              key: ${{ secrets.SSH_PRIVATE_KEY }}
              source: "*,!node_modules"
              target: ${{ secrets.PROJECT_PATH }}
              # strip_components: 0
              # rm: false

         - name: Restart application
           uses: appleboy/ssh-action@master
           with:
              host: ${{ secrets.HOST }}
              username: ${{ secrets.USERNAME }}
              port: 22
              key: ${{ secrets.SSH_PRIVATE_KEY }}
              script: |
                 cd ${{ secrets.PROJECT_PATH }}
                 export NODE_ENV=production

                 # Restart do PM2
                 if pm2 list | grep -q "sistema-gestao-rh"; then
                   cd sistema-gestao-rh
                   yarn
                   pm2 restart sistema-gestao-rh
                 else
                   pm2 start yarn --name "sistema-gestao-rh" -- start
                   pm2 save
                 fi
